services:
  backend_test:
    build:
      dockerfile: tests/backend/Dockerfile.test
      context: .
    command: pytest
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db_test:5432/foodbank_test_db
      - REDIS_URL=redis://redis_test:6379
      - REDIS_CACHE_TIMEOUT=300
    depends_on:
      - redis_test

  redis_test:
    image: redis:alpine
    depends_on:
      db_test:
        condition: service_healthy

  db_test:
    build: ./backend/db-init
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foodbank_test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d foodbank_test_db -U user"]
      interval: 5s
      timeout: 5s
      retries: 5