services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/foodbank_db
    depends_on:
      - db

  db:
    build: ./backend/db-init
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foodbank_db
    ports:
      - "5432:5432"
    volumes:
      - db-persistent-storage:/var/lib/postgresql/data

volumes:
  db-persistent-storage: