services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/foodbank_db
      - REDIS_URL=redis://redis:6379
      - REDIS_CACHE_TIMEOUT=300
    depends_on:
      - redis

  redis:
    image: redis:alpine
    depends_on:
      - db

  db:
    build: ./backend/db-init
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foodbank_db
    ports:
      - "5432:5432"
    volumes:
      - db-persistent-storage:/var/lib/postgresql/data

volumes:
  db-persistent-storage:
